# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[edge_functions]]
  path = "/"
  function = "nothing"

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugins.inputs]
    enable = false